'use strict';

module.exports = {
    registration_create             : "wamp.registration.on_create",
    registration_register           : "wamp.registration.on_register",
    registration_unregister         : "wamp.registration.on_unregister",
    registration_delete             : "wamp.registration.on_delete",
    registration_list               : "wamp.registration.list",
    registration_lookup             : "wamp.registration.lookup",
    registration_match              : "wamp.registration.match",
    registration_get                : "wamp.registration.get",
    registration_list_callees       : "wamp.registration.list_callees",
    registration_count_callees      : "wamp.registration.count_callees",
    subscription_create             : "wamp.subscription.on_create",
    subscription_subscribe          : "wamp.subscription.on_subscribe",
    subscription_unsubscribe        : "wamp.subscription.on_unsubscribe",
    subscription_delete             : "wamp.subscription.on_delete",
    subscription_list               : "wamp.subscription.list",
    subscription_lookup             : "wamp.subscription.lookup",
    subscription_match              : "wamp.subscription.match",
    subscription_get                : "wamp.subscription.get",
    subscription_list_subscribers   : "wamp.subscription.list_subscribers",
    subscription_count_subscribers  : "wamp.subscription.count_subscribers",
    session_join                    : "wamp.session.on_join",
    session_leave                   : "wamp.session.on_leave",
    session_count                   : "wamp.session.count",
    session_list                    : "wamp.session.list",
    session_get                     : "wamp.session.get",
    session_kill                    : "wamp.session.kill",
    session_kill_by_authid          : "wamp.session.kill_by_authid",
    session_kill_by_authrole        : "wamp.session.kill_by_authrole",
    session_kill_all                : "wamp.session.kill_all"
};